name: TU_Ilmenau
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - portaudio
  - ffmpeg
  - librosa
  - notebook
  - numba==0.46.0
  - ipywidgets
  - rise
  - jupyter_nbextensions_configurator
  - jupyter_contrib_nbextensions
  - pyaudio
  - opencv
  - pytorch
  - torchvision

